ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/ProductCategory.cs
namespace ProgramminClass3.MvcLesson.Models
{
    public class ProductCategory
    {
        public int ProductId { get; set; }
        public Product Product { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/ViewModels/ProductCategoryViewModel.cs
using ProgramminClass3.MvcLesson.Models;

namespace ProgramminClass3.MvcLesson.ViewModels
{
    public class ProductCategoryListViewModel
    {
        public List<ProductCategory> ProductCategoies { get; set; }

        public List<Category> Categories { get; set; }

        public int ProductId { get; set; }
        public int CategoryId { get; set; }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductCategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;
using ProgramminClass3.MvcLesson.ViewModels;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductCategoriesController : Controller
    {
        private readonly ApplicationDbContext _dbCotnext;

        public ProductCategoriesController(ApplicationDbContext dbCotnext)
        {
            _dbCotnext = dbCotnext;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var listViewModel = new ProductCategoryListViewModel();

            listViewModel.ProductCategories = _dbCotnext
                .ProductCategories
                .Include(productCategory => productCategory.Category)
                .Where(productCategory => productCategory.ProductId == id)
                .ToList();

            listViewModel.Categories = _dbCotnext.Categories.ToList();
            listViewModel.ProductId = id;

            return View(listViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                _dbCotnext.ProductCategories.Add(productCategory);
                _dbCotnext.SaveChanges();

                return RedirectToAction("Index", new { id = productCategory.ProductId });
            }

            return View(productCategory);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public  ProductCategoryController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index (int id)
        {
            var productCategories = _dbContext
                .ProductCategories
                .Include(productCategory => productCategory.Category)
                .Where(productCategory => productCategory.ProductId == id)
                .ToList();

            ViewBag.Categories = _dbContext.Categories.ToList();
            ViewBag.ProductId = id;

            return View(productCategories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCategory productCategory)
        {
            if(ModelState.IsValid)
            {
                _dbContext.ProductCategories.Add(productCategory);
                _dbContext.SaveChanges();

                return RedirectToAction("Index", new { id = productCategory.ProductId });
            }

            return View(productCategory);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/ProductCategory/Index.cshtml
@model List ProductCategory


<div>
    <div>
        <form asp-controller="ProductCategory" asp-action="Create">
            <input type="hidden" name="ProductId" value="@ViewBag.ProductId" />

            <div class="mb-3">
                <div class="input-group">
                    <select name="CategoryId" class="form-control">
                        <option value="">
                            -- Select Category -- 
                        </option>
                        @foreach(var category in ViewBag.Categories as List<Category>)
                        {
                        <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            Add Category
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach(var productCategory in Model)
            {
            <tr>
                <td>
                    @productCategory.Category.Name
                </td>
                <td>
                    @productCategory.Category.Description
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>