ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/UnitOfMeasure.cs
using System.ComponentModel.DataAnnotations;

namespace ProgramminClass3.MvcLesson.Models
{
    public class UnitOfMeasure
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        
    }

}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/UnitOfMeasures.cs
using System.ComponentModel.DataAnnotations;

namespace ProgramminClass3.MvcLesson.Models
{
    public class UnitOfMeasures
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;


namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductTypesController : Controller
    {
        private ApplicationDbContext _dbContext;

        public ProductTypesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var ProductTypes = _dbContext.ProductTypes.ToList();

            return View(ProductTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductType productType)

        {
            if (ModelState.IsValid)
            {
                _dbContext.ProductTypes.Add(productType);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(productType);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var productType = _dbContext.ProductTypes.Find(id);

            return View(productType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductType productType)
        {
            if (ModelState.IsValid)
            {
                _dbContext.ProductTypes.Update(productType);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(productType);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/UnitOfMeasureController.cs
using Microsoft.AspNetCore.Mvc;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Data.Migrations;
using ProgramminClass3.MvcLesson.Models;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class UnitOfMeasuresController : Controller
    {
        private ApplicationDbContext _dbContext;

        public UnitOfMeasuresController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var UnitOfMeasures = _dbContext.UnitOfMeasures.ToList();

            return View(UnitOfMeasures);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UnitOfMeasure unitOfMeasure)

        {
            if (ModelState.IsValid)
            {
                _dbContext.UnitOfMeasures.Add(unitOfMeasure);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(unitOfMeasure);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var unitOfMeasure = _dbContext.UnitOfMeasures.Find(id);

            return View(unitOfMeasure);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UnitOfMeasure unitOfMeasure)
        {
            if (ModelState.IsValid)
            {
                _dbContext.UnitOfMeasures.Update(unitOfMeasure);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(unitOfMeasure);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/UnitOfMeasuresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Data.Migrations;
using ProgramminClass3.MvcLesson.Models;



namespace ProgramminClass3.MvcLesson.Controllers
{
    public class UnitOfMeasuresController : Controller
    {
        private ApplicationDbContext _dbContext;

        public UnitOfMeasuresController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var UnitOfMeasures = _dbContext.UnitOfMeasures.ToList();

            return View(UnitOfMeasures);
        }


        [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }
            
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UnitOfMeasure unitOfMeasure)

        {
            if (ModelState.IsValid)
            {
                _dbContext.UnitOfMeasures.Add(unitOfMeasure);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(unitOfMeasure);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var unitOfMeasure = _dbContext.UnitOfMeasures.Find(id);

            return View(unitOfMeasure);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UnitOfMeasure unitOfMeasure)
        {
            if (ModelState.IsValid)
            {
                _dbContext.UnitOfMeasures.Update(unitOfMeasure);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(unitOfMeasure);
        }    
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/UnitOfMeasures/Create.cshtml
@model UnitOfMeasure

<div>
    <form asp-controller="UnitOfMeasures" asp-action="Create">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">
                Name
            </label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">
                Description
            </label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div>
            <a asp-controller="UnitOfMeasures" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>

            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>

    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/UnitOfMeasures/Delete.cshtml
@model UnitOfMeasure

<div>
    <dl>
        <dt>
            Id
        </dt>
        <dd>
            @Model.Id
        </dd>

        <dt>
            Name
        </dt>
        <dd>
            @Model.Name
        </dd>

        <dt>
            Description
        </dt>
        <dd>
            @Model.Description
        </dd>
    </dl>

    <p>
        Are You sure that You want to delete this item?
    </p>

    <form asp-controller="UnitOfMeasures" asp-action="Delete" asp-route-id="@Model.Id">
        <div>
            <a asp-controller="UnitOfMeasures" asp-action="Index" class="btn btn-secondary">
                No
            </a>

            <button type="submit" class="btn btn-primary">
                Yes
            </button>
        </div>
    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/UnitOfMeasures/Edit.cshtml
@model UnitOfMeasure

<div>
    <form asp-controller="UnitOfMeasures" asp-action="Edit">
        <div class="mb-3">
            <label asp-for="Id" class="form-label">
                Id
            </label>
            <input asp-for="Id" class="form-control" readonly />
        </div>

        <div class="mb-3">
            <label asp-for="Name" class="form-label">
                Name
            </label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">
                Description
            </label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div>
            <a asp-controller="UnitOfMeasures" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>

    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/UnitOfMeasures/Index.cshtml
@model List<UnitOfMeasure>

<div>
    <a asp-controller="UnitOfMeasures" asp-action="Create" class="btn btn-primary">
        Create
    </a>
    <table class="table">
        <thead>
            <tr>
                <th>Actions</th>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var unitOfMeasure in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="ProductTypes"
                           asp-action="Edit"
                           asp-route-id="@unitOfMeasure.Id"
                           class="btn btn-secondary">
                            Edit
                        </a>
                    </td>
                    <td>
                        @unitOfMeasure.Id
                    </td>
                    <td>
                        @unitOfMeasure.Name
                    </td>
                    <td>
                        @unitOfMeasure.Description
                    </td>
                    <td>
                        <a asp-controller="UnitOfMeasures"
                       asp-action="Edit"
                       asp-route-id="@unitOfMeasure.Id"
                       class="btn btn-secondary">
                            Edit
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>