ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/Color.cs
using System.ComponentModel.DataAnnotations;

namespace ProgramminClass3.MvcLesson.Models
{
    public class Color
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ColorsController.cs
using Microsoft.AspNetCore.Mvc;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ColorsController : Controller
    {
        private ApplicationDbContext _dbContext;

        public ColorsController (ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var colors = _dbContext.Colors.ToList();
            return View(colors);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Color color)
        {
            _dbContext.Colors.Add(color);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            //var product = _dbContext.Colors.Find(id);
            var color = _dbContext
                .Colors
                .FirstOrDefault(p => p.Id == id);

            return View(color);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Color color)
        {
            _dbContext.Colors.Update(color);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Colors/Create.cshtml
@model Color

<div>
    <form asp-controller="Colors" asp-action="Create">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">
                Name
            </label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">
                Description
            </label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div>
            <a asp-controller="Colors" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>

    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Colors/Delete.cshtml
@model Color

<div>
    <dl>
        <dt>
            ID
        </dt>
        <dd>
            @Model.Id
        </dd>

        <dt>
            Name
        </dt>
        <dd>
            @Model.Name
        </dd>

        <dt>
            Description
        </dt>
        <dd>
            @Model.Description
        </dd>
    </dl>

    <p>
        Are you sure that you want to delete this Color
    </p>

    <form asp-controller="Color" asp-action="Delete" asp-route-id="@Model.Id">
        <div>
            <a asp-controller="Color" asp-action="Index" class="btn btn-primary">
                No
            </a>

            <button type="submit" class="btn btn-danger">
                Yes
            </button>
        </div>
    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Colors/Edit.cshtml
@model Color

<div>
    <form asp-controller="Colors" asp-action="Edit">
        <div class="mb-3">
            <label asp-for="Id" class="form-label">
                ID
            </label>
            <input asp-for="Id" class="form-control" readonly />
        </div>

        <div class="mb-3">
            <label asp-for="Name" class="form-label">
                Name
            </label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">
                Description
            </label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>

        <div>
            <a asp-controller="Colors" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>

    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Colors/Index.cshtml
@model List<Color>

<div>
    <a asp-controller="Colors" asp-action="Create" class="btn btn-primary">
        Create
    </a>

    <table class="table">
        <thead>
            <tr>
                <th>Actions</th>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var color in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Colors"
                       asp-action="Edit"
                       asp-route-id="@color.Id"
                       class="btn btn-secondary">
                            Edit
                        </a>
                    </td>
                    <td>
                        @color.Id
                    </td>
                    <td>
                        @color.Name
                    </td>
                    <td>
                        @color.Description
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>