ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/Product.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ProgramminClass3.MvcLesson.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        public decimal UnitPrice { get; set; }

        public int Quantity { get; set; }

        public int? TypeId { get; set; }
        public ProductType Type { get; set; }

        public int? UnitOfMeasureId { get; set; }
        public UnitOfMeasure UnitOfMeasure { get; set; }
        
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Models/ProductType.cs
using System.ComponentModel.DataAnnotations;

namespace ProgramminClass3.MvcLesson.Models
{
    public class ProductType
    {

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        
    }

}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/ViewModels/ProductViewModel.cs
using ProgramminClass3.MvcLesson.Models;
using System.ComponentModel.DataAnnotations;


namespace ProgramminClass3.MvcLesson.ViewModels
{
    public class ProductViewModel
    {
        [Required]
        public Product Product { get; set; }

        public List<ProductType> ProductTypes { get; set; }

       public List<UnitOfMeasure> UnitOfMeasures { get; set; }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductColorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;
using ProgramminClass3.MvcLesson.ViewModels;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductColorsController : Controller
    {
        private readonly ApplicationDbContext _dbCotnext;

        public ProductColorsController(ApplicationDbContext dbContext)
        {
            _dbCotnext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var listViewModel = new ProductColorListViewModel();

            listViewModel.ProductColors = _dbCotnext
                .ProductColors
                .Include(productColor => productColor.Color)
                .Where(productColor => productColor.ProductId == id)
                .ToList();

            listViewModel.Colors = _dbCotnext.Colors.ToList();
            listViewModel.ProductId = id;

            return View(listViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductColor productColor)
        {
            if (ModelState.IsValid)
            {

                _dbCotnext.ProductColors.Add(productColor);
                _dbCotnext.SaveChanges();

                return RedirectToAction("Index", new {id = productColor.ProductId});
            }

            return View(productColor);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductSizesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;
using ProgramminClass3.MvcLesson.ViewModels;

namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductSizesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public ProductSizesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var listViewModel = new ProductSizeListViewModel();

            listViewModel.ProductSizes = _dbContext
                .ProductSizes
                .Include(productSize => productSize.Size)
                .Where(productSize => productSize.ProductId == id)
                .ToList();

            listViewModel.Sizes = _dbContext.Sizes.ToList();
            listViewModel.ProductId = id;

            return View(listViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductSize productSize)
        {
            if (ModelState.IsValid)
            {
                _dbContext.ProductSizes.Add(productSize);
                _dbContext.SaveChanges();

                return RedirectToAction("Index", new { id = productSize.ProductId });
            }

            return View(productSize);
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProgramminClass3.MvcLesson.Data;
using ProgramminClass3.MvcLesson.Models;
using ProgramminClass3.MvcLesson.ViewModels;


namespace ProgramminClass3.MvcLesson.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext _dbContext;

        public ProductsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var products = _dbContext
                .Products
                .Include(product => product.Type)
                .Include(product => product.UnitOfMeasure)
                .ToList();

            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var productViewModel = new ProductViewModel
            {
                ProductTypes = _dbContext.ProductTypes.ToList(),
                UnitOfMeasures = _dbContext.UnitOfMeasures.ToList()
            };
           
            return View(productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Products.Add(productViewModel.Product);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            productViewModel.ProductTypes = _dbContext.ProductTypes.ToList();
            productViewModel.UnitOfMeasures = _dbContext.UnitOfMeasures.ToList();

            return View(productViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var productViewModel = new ProductViewModel
            {
                Product = _dbContext.Products.Find(id),
                ProductTypes = _dbContext.ProductTypes.ToList(),
                UnitOfMeasures = _dbContext.UnitOfMeasures.ToList()
            };

            return View(productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Products.Update(productViewModel.Product);
                _dbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            productViewModel.ProductTypes = _dbContext.ProductTypes.ToList();
            productViewModel.UnitOfMeasures = _dbContext.UnitOfMeasures.ToList();

            return View(productViewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = _dbContext.Products.Find(id);

            ViewBag.UnitOfMeasures = _dbContext.UnitOfMeasures.ToList();

            return View(product);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCofirmed(int id)
        {
            var product = _dbContext.Products.Find(id);

            _dbContext.Products.Remove(product);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Products/Create.cshtml
@model ProductViewModel

<div>
    <form asp-controller="Products" asp-action="Create">
        <div class="mb-3">
            <label asp-for="Product.Name" class="form-label">
                Name
            </label>
            <input asp-for="Product.Name" class="form-control" />
            <span asp-validation-for="Product.Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Product.Description" class="form-label">
                Description
            </label>
            <textarea asp-for="Product.Description" class="form-control"></textarea>
            <span asp-validation-for="Product.Description" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Product.UnitPrice" class="form-label">
                Unit Price
            </label>
            <input asp-for="Product.UnitPrice" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Product.Quantity" class="form-label">
                Quantity
            </label>
            <input asp-for="Product.Quantity" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Product.TypeId" class="form-label">
                Type
            </label>
            <select asp-for="Product.TypeId" class="form-control">
                <option value="">
                    Please Select
                </option>

                @foreach(var type in Model.ProductTypes)
                {
                    <option value="@type.Id">
                        @type.Name
                    </option>
                           
                }
            </select>
        </div>
        
        <div class="mb-3">
            <label name="unitOfMeasureId" class="form-label">
               Unit Of Measure
            </label>
            <select name="unitOfMeasurId" class="form-control">
                <option value="">
                    Please Select
                </option>
                
                @foreach (var type in Model.UnitOfMeasures)
                {
                    <option value="@type.Id">@type.Name</option>
                }
            </select>
        </div>
        
        <div>
            <a asp-controller="Products" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>

            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>
    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Products/Delete.cshtml
@model Product

<div>
    <dl>
        
        <dt>
            ID
        </dt>
        <dd>
            @Model.Id
        </dd>

        <dt>
            Name
        </dt>
        <dd>
            @Model.Name
        </dd>

        <dt>
            Description
        </dt>
        <dd>
            @Model.Description
        </dd>

        <dt>
            Quantity
        </dt>
        <dd>
            @Model.Quantity
        </dd>

        <dt>
            Unit Price
        </dt>
        <dd>
            @Model.UnitPrice
        </dd>
    </dl>

    <p>
        Are you sure that you want to delete this product?
    </p>

   <form asp-controller="Products" asp-action="Delete" asp-route-id="@Model.Id">
        <div>
            <a asp-controller="Products" asp-action="Index" class="btn btn-secondary">
                No
            </a>

            <button type="submit" class="btn btn-primary">
                Yes
            </button>
        </div>
   </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Products/Edit.cshtml
@model ProductViewModel

<div>
    <form asp-controller="Products" asp-action="Edit">
        <div class="mb-3">
            <label asp-for="Product.Id" class="form-label">
                ID
            </label>
            <input asp-for="Product.Id" class="form-control" readonly />
        </div>

        <div class="mb-3">
            <label asp-for="Product.Name" class="form-label">
                Name
            </label>
            <input asp-for="Product.Name" class="form-control" />
            <span asp-validation-for="Product.Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Product.Description" class="form-label">
                Description
            </label>
            <textarea asp-for="Product.Description" class="form-control"></textarea>
            <span asp-validation-for="Product.Description" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Product.UnitPrice" class="form-label">
                Unit Price
            </label>
            <input asp-for="Product.UnitPrice" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Product.Quantity" class="form-label">
                Quantity
            </label>
            <input asp-for="Product.Quantity" class="form-control" />
        </div>
        
        <div class="mb-3">
            <label asp-for="Product.TypeId" class="form-label">
                Type
            </label>
            <select asp-for="Product.TypeId" class="form-control">
                <option value="">
                    Please Select
                </option>

                @foreach(var type in Model.ProductTypes)
                {
                    <option value="@type.Id">@type.Name</option>
                }
            </select>
        </div>

        <div class="mb-3">
            <label name="UnitOfMeasureId" class="form-label">
                Unit Of Measure
            </label>
            <select name="UnitOfMeasureId" class="form-control">
                <option value="">
                    Please Select
                </option>

                @foreach (var type in Model.UnitOfMeasures)
                {
                    <option value="@type.Id">@type.Name</option>
                }
            </select>
        </div>
        
        

        <div class="mb-3">
            <a asp-controller="ProductCategories" 
                asp-action="Index" 
                asp-route-id="@Model.Product.Id">
                Categories
            </a>
        </div>
        <div class="mb-3">
            <a asp-controller="ProductColors"
               asp-action="Index"
               asp-route-id="@Model.Product.Id">
                Colors
            </a>
        </div>
        <div class="mb-3">
            <a asp-controller="ProductSizes"
               asp-action="Index"
               asp-route-id="@Model.Product.Id">
                Sizes
            </a>
        </div>

        <div>
            <a asp-controller="Products" asp-action="Index" class="btn btn-secondary">
                Cancel
            </a>
            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </div>
    </form>
</div>

ProgramminClass3.MvcLesson/ProgramminClass3.MvcLesson/Views/Products/Index.cshtml
@model List<Product>

<div>
    <a asp-controller="Products" asp-action="Create" class="btn btn-primary">
        Create
    </a>

    <table class="table">
        <thead>
            <tr>
                <th>Actions</th>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Type</th>
                <th>Measure</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Products" 
                            asp-action="Edit" 
                            asp-route-id="@product.Id"
                            class="btn btn-secondary">
                            Edit
                        </a>

                        <a asp-controller="Products"
                            asp-action="Delete"
                            asp-route-id="@product.Id"
                            class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                    <td>
                        @product.Id
                    </td>
                    <td>
                        @product.Name
                    </td>
                    <td>
                        @product.Description
                    </td>
                    <td>
                        @product.UnitPrice
                    </td>
                    <td>
                        @product.Quantity
                    </td>
                    <td>
                        @product.Type?.Name
                    </td>
                    <td>
                        @product.UnitOfMeasure?.Name
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>